//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package net.digistar.vanadio.model;

// import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}plot"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}itemLabel" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}categoryAxisLabelExpression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}categoryAxisFormat" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}valueAxisLabelExpression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}valueAxisFormat" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}domainAxisMinValueExpression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}domainAxisMaxValueExpression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}rangeAxisMinValueExpression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}rangeAxisMaxValueExpression" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="isShowLabels"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="isShowTickMarks"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="isShowTickLabels"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
// @XmlAccessorType(XmlAccessType.FIELD)
//
// @XmlRootElement(name = "barPlot", namespace = "http://jasperreports.sourceforge.net/jasperreports")
import com.abubusoft.kripton.annotation.BindType;
import com.abubusoft.kripton.annotation.BindXml;
import com.abubusoft.kripton.xml.XmlType;

@BindType
public class  BarPlot {

    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports", required = true)
    public Plot plot;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public ItemLabel itemLabel;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public CategoryAxisLabelExpression categoryAxisLabelExpression;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public CategoryAxisFormat categoryAxisFormat;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public ValueAxisLabelExpression valueAxisLabelExpression;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public ValueAxisFormat valueAxisFormat;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public DomainAxisMinValueExpression domainAxisMinValueExpression;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public DomainAxisMaxValueExpression domainAxisMaxValueExpression;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public RangeAxisMinValueExpression rangeAxisMinValueExpression;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public RangeAxisMaxValueExpression rangeAxisMaxValueExpression;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isShowLabels")
    public String isShowLabels;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isShowTickMarks")
    public String isShowTickMarks;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isShowTickLabels")
    public String isShowTickLabels;

    /**
     * Gets the value of the plot property.
     *
     * @return possible object is
     * {@link Plot }
     */
    public Plot getPlot() {
        return plot;
    }

    /**
     * Sets the value of the plot property.
     *
     * @param value allowed object is
     *              {@link Plot }
     */
    public void setPlot(Plot value) {
        this.plot = value;
    }

    /**
     * Gets the value of the itemLabel property.
     *
     * @return possible object is
     * {@link ItemLabel }
     */
    public ItemLabel getItemLabel() {
        return itemLabel;
    }

    /**
     * Sets the value of the itemLabel property.
     *
     * @param value allowed object is
     *              {@link ItemLabel }
     */
    public void setItemLabel(ItemLabel value) {
        this.itemLabel = value;
    }

    /**
     * Gets the value of the categoryAxisLabelExpression property.
     *
     * @return possible object is
     * {@link CategoryAxisLabelExpression }
     */
    public CategoryAxisLabelExpression getCategoryAxisLabelExpression() {
        return categoryAxisLabelExpression;
    }

    /**
     * Sets the value of the categoryAxisLabelExpression property.
     *
     * @param value allowed object is
     *              {@link CategoryAxisLabelExpression }
     */
    public void setCategoryAxisLabelExpression(CategoryAxisLabelExpression value) {
        this.categoryAxisLabelExpression = value;
    }

    /**
     * Gets the value of the categoryAxisFormat property.
     *
     * @return possible object is
     * {@link CategoryAxisFormat }
     */
    public CategoryAxisFormat getCategoryAxisFormat() {
        return categoryAxisFormat;
    }

    /**
     * Sets the value of the categoryAxisFormat property.
     *
     * @param value allowed object is
     *              {@link CategoryAxisFormat }
     */
    public void setCategoryAxisFormat(CategoryAxisFormat value) {
        this.categoryAxisFormat = value;
    }

    /**
     * Gets the value of the valueAxisLabelExpression property.
     *
     * @return possible object is
     * {@link ValueAxisLabelExpression }
     */
    public ValueAxisLabelExpression getValueAxisLabelExpression() {
        return valueAxisLabelExpression;
    }

    /**
     * Sets the value of the valueAxisLabelExpression property.
     *
     * @param value allowed object is
     *              {@link ValueAxisLabelExpression }
     */
    public void setValueAxisLabelExpression(ValueAxisLabelExpression value) {
        this.valueAxisLabelExpression = value;
    }

    /**
     * Gets the value of the valueAxisFormat property.
     *
     * @return possible object is
     * {@link ValueAxisFormat }
     */
    public ValueAxisFormat getValueAxisFormat() {
        return valueAxisFormat;
    }

    /**
     * Sets the value of the valueAxisFormat property.
     *
     * @param value allowed object is
     *              {@link ValueAxisFormat }
     */
    public void setValueAxisFormat(ValueAxisFormat value) {
        this.valueAxisFormat = value;
    }

    /**
     * Gets the value of the domainAxisMinValueExpression property.
     *
     * @return possible object is
     * {@link DomainAxisMinValueExpression }
     */
    public DomainAxisMinValueExpression getDomainAxisMinValueExpression() {
        return domainAxisMinValueExpression;
    }

    /**
     * Sets the value of the domainAxisMinValueExpression property.
     *
     * @param value allowed object is
     *              {@link DomainAxisMinValueExpression }
     */
    public void setDomainAxisMinValueExpression(DomainAxisMinValueExpression value) {
        this.domainAxisMinValueExpression = value;
    }

    /**
     * Gets the value of the domainAxisMaxValueExpression property.
     *
     * @return possible object is
     * {@link DomainAxisMaxValueExpression }
     */
    public DomainAxisMaxValueExpression getDomainAxisMaxValueExpression() {
        return domainAxisMaxValueExpression;
    }

    /**
     * Sets the value of the domainAxisMaxValueExpression property.
     *
     * @param value allowed object is
     *              {@link DomainAxisMaxValueExpression }
     */
    public void setDomainAxisMaxValueExpression(DomainAxisMaxValueExpression value) {
        this.domainAxisMaxValueExpression = value;
    }

    /**
     * Gets the value of the rangeAxisMinValueExpression property.
     *
     * @return possible object is
     * {@link RangeAxisMinValueExpression }
     */
    public RangeAxisMinValueExpression getRangeAxisMinValueExpression() {
        return rangeAxisMinValueExpression;
    }

    /**
     * Sets the value of the rangeAxisMinValueExpression property.
     *
     * @param value allowed object is
     *              {@link RangeAxisMinValueExpression }
     */
    public void setRangeAxisMinValueExpression(RangeAxisMinValueExpression value) {
        this.rangeAxisMinValueExpression = value;
    }

    /**
     * Gets the value of the rangeAxisMaxValueExpression property.
     *
     * @return possible object is
     * {@link RangeAxisMaxValueExpression }
     */
    public RangeAxisMaxValueExpression getRangeAxisMaxValueExpression() {
        return rangeAxisMaxValueExpression;
    }

    /**
     * Sets the value of the rangeAxisMaxValueExpression property.
     *
     * @param value allowed object is
     *              {@link RangeAxisMaxValueExpression }
     */
    public void setRangeAxisMaxValueExpression(RangeAxisMaxValueExpression value) {
        this.rangeAxisMaxValueExpression = value;
    }

    /**
     * Gets the value of the isShowLabels property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsShowLabels() {
        return isShowLabels;
    }

    /**
     * Sets the value of the isShowLabels property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsShowLabels(String value) {
        this.isShowLabels = value;
    }

    /**
     * Gets the value of the isShowTickMarks property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsShowTickMarks() {
        return isShowTickMarks;
    }

    /**
     * Sets the value of the isShowTickMarks property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsShowTickMarks(String value) {
        this.isShowTickMarks = value;
    }

    /**
     * Gets the value of the isShowTickLabels property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsShowTickLabels() {
        return isShowTickLabels;
    }

    /**
     * Sets the value of the isShowTickLabels property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsShowTickLabels(String value) {
        this.isShowTickLabels = value;
    }

}
