//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package net.digistar.vanadio.model;

// import javax.xml.bind.annotation.*;


import com.abubusoft.kripton.annotation.BindXml;
import com.abubusoft.kripton.xml.XmlType;

/**
 * <p>Java class for commonReturnValue complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="commonReturnValue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="toVariable" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="calculation" default="Nothing"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Nothing"/&gt;
 *             &lt;enumeration value="Count"/&gt;
 *             &lt;enumeration value="DistinctCount"/&gt;
 *             &lt;enumeration value="Sum"/&gt;
 *             &lt;enumeration value="Average"/&gt;
 *             &lt;enumeration value="Lowest"/&gt;
 *             &lt;enumeration value="Highest"/&gt;
 *             &lt;enumeration value="StandardDeviation"/&gt;
 *             &lt;enumeration value="Variance"/&gt;
 *             &lt;enumeration value="First"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="incrementerFactoryClass" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
// @XmlAccessorType(XmlAccessType.FIELD)
//
//@XmlSeeAlso({
//        VariableReturnValue.class,
//        ExpressionReturnValue.class
//})
public abstract class CommonReturnValue {

    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "toVariable")
    public String toVariable;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "calculation")
    public String calculation;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "incrementerFactoryClass")
    public String incrementerFactoryClass;

    /**
     * Gets the value of the toVariable property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getToVariable() {
        return toVariable;
    }

    /**
     * Sets the value of the toVariable property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setToVariable(String value) {
        this.toVariable = value;
    }

    /**
     * Gets the value of the calculation property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCalculation() {
        if (calculation == null) {
            return "Nothing";
        } else {
            return calculation;
        }
    }

    /**
     * Sets the value of the calculation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCalculation(String value) {
        this.calculation = value;
    }

    /**
     * Gets the value of the incrementerFactoryClass property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIncrementerFactoryClass() {
        return incrementerFactoryClass;
    }

    /**
     * Sets the value of the incrementerFactoryClass property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIncrementerFactoryClass(String value) {
        this.incrementerFactoryClass = value;
    }

}
