//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package net.digistar.vanadio.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}cellContents" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="rowTotalGroup" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="columnTotalGroup" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "cellContents"
})
@XmlRootElement(name = "crosstabCell", namespace = "http://jasperreports.sourceforge.net/jasperreports")
//@BindType
public class CrosstabCell {

    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected CellContents cellContents;
    @XmlAttribute(name = "width")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String width;
    @XmlAttribute(name = "height")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String height;
    @XmlAttribute(name = "rowTotalGroup")
    protected String rowTotalGroup;
    @XmlAttribute(name = "columnTotalGroup")
    protected String columnTotalGroup;

    /**
     * Gets the value of the cellContents property.
     *
     * @return possible object is
     * {@link CellContents }
     */
    public CellContents getCellContents() {
        return cellContents;
    }

    /**
     * Sets the value of the cellContents property.
     *
     * @param value allowed object is
     *              {@link CellContents }
     */
    public void setCellContents(CellContents value) {
        this.cellContents = value;
    }

    /**
     * Gets the value of the width property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the rowTotalGroup property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRowTotalGroup() {
        return rowTotalGroup;
    }

    /**
     * Sets the value of the rowTotalGroup property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRowTotalGroup(String value) {
        this.rowTotalGroup = value;
    }

    /**
     * Gets the value of the columnTotalGroup property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getColumnTotalGroup() {
        return columnTotalGroup;
    }

    /**
     * Sets the value of the columnTotalGroup property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setColumnTotalGroup(String value) {
        this.columnTotalGroup = value;
    }

}
