//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package net.digistar.vanadio.model;

import com.abubusoft.kripton.annotation.BindType;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}plot"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}itemLabel" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="isShowLabels"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="depthFactor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isCircular"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="labelFormat" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="legendLabelFormat" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "plot",
        "itemLabel"
})
@XmlRootElement(name = "pie3DPlot", namespace = "http://jasperreports.sourceforge.net/jasperreports")
@BindType
public class Pie3DPlot {

    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports", required = true)
    protected Plot plot;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected ItemLabel itemLabel;
    @XmlAttribute(name = "isShowLabels")
    protected String isShowLabels;
    @XmlAttribute(name = "depthFactor")
    protected String depthFactor;
    @XmlAttribute(name = "isCircular")
    protected String isCircular;
    @XmlAttribute(name = "labelFormat")
    protected String labelFormat;
    @XmlAttribute(name = "legendLabelFormat")
    protected String legendLabelFormat;

    /**
     * Gets the value of the plot property.
     *
     * @return possible object is
     * {@link Plot }
     */
    public Plot getPlot() {
        return plot;
    }

    /**
     * Sets the value of the plot property.
     *
     * @param value allowed object is
     *              {@link Plot }
     */
    public void setPlot(Plot value) {
        this.plot = value;
    }

    /**
     * Gets the value of the itemLabel property.
     *
     * @return possible object is
     * {@link ItemLabel }
     */
    public ItemLabel getItemLabel() {
        return itemLabel;
    }

    /**
     * Sets the value of the itemLabel property.
     *
     * @param value allowed object is
     *              {@link ItemLabel }
     */
    public void setItemLabel(ItemLabel value) {
        this.itemLabel = value;
    }

    /**
     * Gets the value of the isShowLabels property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsShowLabels() {
        return isShowLabels;
    }

    /**
     * Sets the value of the isShowLabels property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsShowLabels(String value) {
        this.isShowLabels = value;
    }

    /**
     * Gets the value of the depthFactor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDepthFactor() {
        return depthFactor;
    }

    /**
     * Sets the value of the depthFactor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDepthFactor(String value) {
        this.depthFactor = value;
    }

    /**
     * Gets the value of the isCircular property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsCircular() {
        return isCircular;
    }

    /**
     * Sets the value of the isCircular property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsCircular(String value) {
        this.isCircular = value;
    }

    /**
     * Gets the value of the labelFormat property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLabelFormat() {
        return labelFormat;
    }

    /**
     * Sets the value of the labelFormat property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLabelFormat(String value) {
        this.labelFormat = value;
    }

    /**
     * Gets the value of the legendLabelFormat property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLegendLabelFormat() {
        return legendLabelFormat;
    }

    /**
     * Sets the value of the legendLabelFormat property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLegendLabelFormat(String value) {
        this.legendLabelFormat = value;
    }

}
