//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package net.digistar.vanadio.model;

// import javax.xml.bind.annotation.*;
import com.abubusoft.kripton.annotation.BindAdapter;
import com.abubusoft.kripton.annotation.BindXml;
import com.abubusoft.kripton.xml.XmlType;
import net.digistar.vanadio.support.CollapsedStringAdapter;
// import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}pen" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}box" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}paragraph" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}conditionalStyle" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isDefault"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="style" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mode"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Opaque"/&gt;
 *             &lt;enumeration value="Transparent"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="forecolor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="backcolor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="pen"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="None"/&gt;
 *             &lt;enumeration value="Thin"/&gt;
 *             &lt;enumeration value="1Point"/&gt;
 *             &lt;enumeration value="2Point"/&gt;
 *             &lt;enumeration value="4Point"/&gt;
 *             &lt;enumeration value="Dotted"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="fill"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Solid"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="radius" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="scaleImage"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Clip"/&gt;
 *             &lt;enumeration value="FillFrame"/&gt;
 *             &lt;enumeration value="RetainShape"/&gt;
 *             &lt;enumeration value="RealHeight"/&gt;
 *             &lt;enumeration value="RealSize"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="hAlign"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Left"/&gt;
 *             &lt;enumeration value="Center"/&gt;
 *             &lt;enumeration value="Right"/&gt;
 *             &lt;enumeration value="Justified"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="hTextAlign"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Left"/&gt;
 *             &lt;enumeration value="Center"/&gt;
 *             &lt;enumeration value="Right"/&gt;
 *             &lt;enumeration value="Justified"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="hImageAlign"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Left"/&gt;
 *             &lt;enumeration value="Center"/&gt;
 *             &lt;enumeration value="Right"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="vAlign"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Top"/&gt;
 *             &lt;enumeration value="Middle"/&gt;
 *             &lt;enumeration value="Bottom"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="vTextAlign"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Top"/&gt;
 *             &lt;enumeration value="Middle"/&gt;
 *             &lt;enumeration value="Bottom"/&gt;
 *             &lt;enumeration value="Justified"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="vImageAlign"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Top"/&gt;
 *             &lt;enumeration value="Middle"/&gt;
 *             &lt;enumeration value="Bottom"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="border"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="None"/&gt;
 *             &lt;enumeration value="Thin"/&gt;
 *             &lt;enumeration value="1Point"/&gt;
 *             &lt;enumeration value="2Point"/&gt;
 *             &lt;enumeration value="4Point"/&gt;
 *             &lt;enumeration value="Dotted"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="borderColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="padding" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="topBorder"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="None"/&gt;
 *             &lt;enumeration value="Thin"/&gt;
 *             &lt;enumeration value="1Point"/&gt;
 *             &lt;enumeration value="2Point"/&gt;
 *             &lt;enumeration value="4Point"/&gt;
 *             &lt;enumeration value="Dotted"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="topBorderColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="topPadding" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="leftBorder"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="None"/&gt;
 *             &lt;enumeration value="Thin"/&gt;
 *             &lt;enumeration value="1Point"/&gt;
 *             &lt;enumeration value="2Point"/&gt;
 *             &lt;enumeration value="4Point"/&gt;
 *             &lt;enumeration value="Dotted"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="leftBorderColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="leftPadding" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="bottomBorder"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="None"/&gt;
 *             &lt;enumeration value="Thin"/&gt;
 *             &lt;enumeration value="1Point"/&gt;
 *             &lt;enumeration value="2Point"/&gt;
 *             &lt;enumeration value="4Point"/&gt;
 *             &lt;enumeration value="Dotted"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="bottomBorderColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bottomPadding" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="rightBorder"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="None"/&gt;
 *             &lt;enumeration value="Thin"/&gt;
 *             &lt;enumeration value="1Point"/&gt;
 *             &lt;enumeration value="2Point"/&gt;
 *             &lt;enumeration value="4Point"/&gt;
 *             &lt;enumeration value="Dotted"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="rightBorderColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="rightPadding" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="rotation"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="None"/&gt;
 *             &lt;enumeration value="Left"/&gt;
 *             &lt;enumeration value="Right"/&gt;
 *             &lt;enumeration value="UpsideDown"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="lineSpacing"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Single"/&gt;
 *             &lt;enumeration value="1_1_2"/&gt;
 *             &lt;enumeration value="Double"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="isStyledText"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="markup" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fontName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fontSize" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="isBold"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="isItalic"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="isUnderline"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="isStrikeThrough"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="pdfFontName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="pdfEncoding" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isPdfEmbedded"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isBlankWhenNull"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
// @XmlAccessorType(XmlAccessType.FIELD)
//
// @XmlRootElement(name = "style", namespace = "http://jasperreports.sourceforge.net/jasperreports")
import com.abubusoft.kripton.annotation.BindType;
import com.abubusoft.kripton.annotation.BindXml;
import com.abubusoft.kripton.xml.XmlType;

@BindType
public class  Style {

    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public Pen pen;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public Box box;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public Paragraph paragraph;
    // @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    public List<ConditionalStyle> conditionalStyle;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "name")
    public String name;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isDefault")
    public String isDefault;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "style")
    public String style;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "mode")
    public String mode;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "forecolor")
    public String forecolor;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "backcolor")
    public String backcolor;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "pen")
    public String stylePen;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "fill")
    public String fill;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "radius")
    @BindAdapter(adapter=CollapsedStringAdapter.class)
    // // @XmlSchemaType(name = "NMTOKEN")
    public String radius;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "scaleImage")
    public String scaleImage;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "hAlign")
    public String hAlign;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "hTextAlign")
    public String hTextAlign;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "hImageAlign")
    public String hImageAlign;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "vAlign")
    public String vAlign;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "vTextAlign")
    public String vTextAlign;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "vImageAlign")
    public String vImageAlign;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "border")
    public String border;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "borderColor")
    public String borderColor;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "padding")
    @BindAdapter(adapter=CollapsedStringAdapter.class)
    // // @XmlSchemaType(name = "NMTOKEN")
    public String padding;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "topBorder")
    public String topBorder;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "topBorderColor")
    public String topBorderColor;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "topPadding")
    @BindAdapter(adapter=CollapsedStringAdapter.class)
    // // @XmlSchemaType(name = "NMTOKEN")
    public String topPadding;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "leftBorder")
    public String leftBorder;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "leftBorderColor")
    public String leftBorderColor;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "leftPadding")
    @BindAdapter(adapter=CollapsedStringAdapter.class)
    // // @XmlSchemaType(name = "NMTOKEN")
    public String leftPadding;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "bottomBorder")
    public String bottomBorder;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "bottomBorderColor")
    public String bottomBorderColor;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "bottomPadding")
    @BindAdapter(adapter=CollapsedStringAdapter.class)
    // // @XmlSchemaType(name = "NMTOKEN")
    public String bottomPadding;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "rightBorder")
    public String rightBorder;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "rightBorderColor")
    public String rightBorderColor;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "rightPadding")
    @BindAdapter(adapter=CollapsedStringAdapter.class)
    // // @XmlSchemaType(name = "NMTOKEN")
    public String rightPadding;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "rotation")
    public String rotation;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "lineSpacing")
    public String lineSpacing;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isStyledText")
    public String isStyledText;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "markup")
    public String markup;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "fontName")
    public String fontName;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "fontSize")
    @BindAdapter(adapter=CollapsedStringAdapter.class)
    // // @XmlSchemaType(name = "NMTOKEN")
    public String fontSize;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isBold")
    public String isBold;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isItalic")
    public String isItalic;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isUnderline")
    public String isUnderline;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isStrikeThrough")
    public String isStrikeThrough;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "pdfFontName")
    public String pdfFontName;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "pdfEncoding")
    public String pdfEncoding;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isPdfEmbedded")
    public String isPdfEmbedded;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "pattern")
    public String pattern;
    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "isBlankWhenNull")
    public String isBlankWhenNull;

    public void sethAlign(String hAlign) {
        this.hAlign = hAlign;
    }

    public void sethTextAlign(String hTextAlign) {
        this.hTextAlign = hTextAlign;
    }

    public void sethImageAlign(String hImageAlign) {
        this.hImageAlign = hImageAlign;
    }

    public void setvAlign(String vAlign) {
        this.vAlign = vAlign;
    }

    public void setvTextAlign(String vTextAlign) {
        this.vTextAlign = vTextAlign;
    }

    public void setvImageAlign(String vImageAlign) {
        this.vImageAlign = vImageAlign;
    }

    /**
     * Gets the value of the pen property.
     *
     * @return possible object is
     * {@link Pen }
     */
    public Pen getPen() {
        return pen;
    }

    /**
     * Sets the value of the pen property.
     *
     * @param value allowed object is
     *              {@link Pen }
     */
    public void setPen(Pen value) {
        this.pen = value;
    }

    /**
     * Gets the value of the box property.
     *
     * @return possible object is
     * {@link Box }
     */
    public Box getBox() {
        return box;
    }

    /**
     * Sets the value of the box property.
     *
     * @param value allowed object is
     *              {@link Box }
     */
    public void setBox(Box value) {
        this.box = value;
    }

    /**
     * Gets the value of the paragraph property.
     *
     * @return possible object is
     * {@link Paragraph }
     */
    public Paragraph getParagraph() {
        return paragraph;
    }

    /**
     * Sets the value of the paragraph property.
     *
     * @param value allowed object is
     *              {@link Paragraph }
     */
    public void setParagraph(Paragraph value) {
        this.paragraph = value;
    }

    /**
     * Gets the value of the conditionalStyle property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conditionalStyle property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConditionalStyle().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConditionalStyle }
     */
    public List<ConditionalStyle> getConditionalStyle() {
        if (conditionalStyle == null) {
            conditionalStyle = new ArrayList<ConditionalStyle>();
        }
        return this.conditionalStyle;
    }

    public void setConditionalStyle(List<ConditionalStyle> conditionalStyle) {
        this.conditionalStyle = conditionalStyle;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isDefault property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * Sets the value of the isDefault property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsDefault(String value) {
        this.isDefault = value;
    }

    /**
     * Gets the value of the style property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the mode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the forecolor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getForecolor() {
        return forecolor;
    }

    /**
     * Sets the value of the forecolor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setForecolor(String value) {
        this.forecolor = value;
    }

    /**
     * Gets the value of the backcolor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBackcolor() {
        return backcolor;
    }

    /**
     * Sets the value of the backcolor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBackcolor(String value) {
        this.backcolor = value;
    }

    /**
     * Gets the value of the stylePen property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStylePen() {
        return stylePen;
    }

    /**
     * Sets the value of the stylePen property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStylePen(String value) {
        this.stylePen = value;
    }

    /**
     * Gets the value of the fill property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFill(String value) {
        this.fill = value;
    }

    /**
     * Gets the value of the radius property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRadius(String value) {
        this.radius = value;
    }

    /**
     * Gets the value of the scaleImage property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScaleImage() {
        return scaleImage;
    }

    /**
     * Sets the value of the scaleImage property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScaleImage(String value) {
        this.scaleImage = value;
    }

    /**
     * Gets the value of the hAlign property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHAlign() {
        return hAlign;
    }

    /**
     * Sets the value of the hAlign property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHAlign(String value) {
        this.hAlign = value;
    }

    /**
     * Gets the value of the hTextAlign property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHTextAlign() {
        return hTextAlign;
    }

    /**
     * Sets the value of the hTextAlign property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHTextAlign(String value) {
        this.hTextAlign = value;
    }

    /**
     * Gets the value of the hImageAlign property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHImageAlign() {
        return hImageAlign;
    }

    /**
     * Sets the value of the hImageAlign property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHImageAlign(String value) {
        this.hImageAlign = value;
    }

    /**
     * Gets the value of the vAlign property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVAlign() {
        return vAlign;
    }

    /**
     * Sets the value of the vAlign property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVAlign(String value) {
        this.vAlign = value;
    }

    /**
     * Gets the value of the vTextAlign property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVTextAlign() {
        return vTextAlign;
    }

    /**
     * Sets the value of the vTextAlign property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVTextAlign(String value) {
        this.vTextAlign = value;
    }

    /**
     * Gets the value of the vImageAlign property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVImageAlign() {
        return vImageAlign;
    }

    /**
     * Sets the value of the vImageAlign property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVImageAlign(String value) {
        this.vImageAlign = value;
    }

    /**
     * Gets the value of the border property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBorder() {
        return border;
    }

    /**
     * Sets the value of the border property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBorder(String value) {
        this.border = value;
    }

    /**
     * Gets the value of the borderColor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBorderColor() {
        return borderColor;
    }

    /**
     * Sets the value of the borderColor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBorderColor(String value) {
        this.borderColor = value;
    }

    /**
     * Gets the value of the padding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPadding() {
        return padding;
    }

    /**
     * Sets the value of the padding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPadding(String value) {
        this.padding = value;
    }

    /**
     * Gets the value of the topBorder property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTopBorder() {
        return topBorder;
    }

    /**
     * Sets the value of the topBorder property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTopBorder(String value) {
        this.topBorder = value;
    }

    /**
     * Gets the value of the topBorderColor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTopBorderColor() {
        return topBorderColor;
    }

    /**
     * Sets the value of the topBorderColor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTopBorderColor(String value) {
        this.topBorderColor = value;
    }

    /**
     * Gets the value of the topPadding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTopPadding() {
        return topPadding;
    }

    /**
     * Sets the value of the topPadding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTopPadding(String value) {
        this.topPadding = value;
    }

    /**
     * Gets the value of the leftBorder property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLeftBorder() {
        return leftBorder;
    }

    /**
     * Sets the value of the leftBorder property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLeftBorder(String value) {
        this.leftBorder = value;
    }

    /**
     * Gets the value of the leftBorderColor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLeftBorderColor() {
        return leftBorderColor;
    }

    /**
     * Sets the value of the leftBorderColor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLeftBorderColor(String value) {
        this.leftBorderColor = value;
    }

    /**
     * Gets the value of the leftPadding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLeftPadding() {
        return leftPadding;
    }

    /**
     * Sets the value of the leftPadding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLeftPadding(String value) {
        this.leftPadding = value;
    }

    /**
     * Gets the value of the bottomBorder property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBottomBorder() {
        return bottomBorder;
    }

    /**
     * Sets the value of the bottomBorder property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBottomBorder(String value) {
        this.bottomBorder = value;
    }

    /**
     * Gets the value of the bottomBorderColor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBottomBorderColor() {
        return bottomBorderColor;
    }

    /**
     * Sets the value of the bottomBorderColor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBottomBorderColor(String value) {
        this.bottomBorderColor = value;
    }

    /**
     * Gets the value of the bottomPadding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBottomPadding() {
        return bottomPadding;
    }

    /**
     * Sets the value of the bottomPadding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBottomPadding(String value) {
        this.bottomPadding = value;
    }

    /**
     * Gets the value of the rightBorder property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRightBorder() {
        return rightBorder;
    }

    /**
     * Sets the value of the rightBorder property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRightBorder(String value) {
        this.rightBorder = value;
    }

    /**
     * Gets the value of the rightBorderColor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRightBorderColor() {
        return rightBorderColor;
    }

    /**
     * Sets the value of the rightBorderColor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRightBorderColor(String value) {
        this.rightBorderColor = value;
    }

    /**
     * Gets the value of the rightPadding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRightPadding() {
        return rightPadding;
    }

    /**
     * Sets the value of the rightPadding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRightPadding(String value) {
        this.rightPadding = value;
    }

    /**
     * Gets the value of the rotation property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRotation() {
        return rotation;
    }

    /**
     * Sets the value of the rotation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRotation(String value) {
        this.rotation = value;
    }

    /**
     * Gets the value of the lineSpacing property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLineSpacing() {
        return lineSpacing;
    }

    /**
     * Sets the value of the lineSpacing property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLineSpacing(String value) {
        this.lineSpacing = value;
    }

    /**
     * Gets the value of the isStyledText property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsStyledText() {
        return isStyledText;
    }

    /**
     * Sets the value of the isStyledText property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsStyledText(String value) {
        this.isStyledText = value;
    }

    /**
     * Gets the value of the markup property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMarkup() {
        return markup;
    }

    /**
     * Sets the value of the markup property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMarkup(String value) {
        this.markup = value;
    }

    /**
     * Gets the value of the fontName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFontName() {
        return fontName;
    }

    /**
     * Sets the value of the fontName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFontName(String value) {
        this.fontName = value;
    }

    /**
     * Gets the value of the fontSize property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFontSize(String value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the isBold property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsBold() {
        return isBold;
    }

    /**
     * Sets the value of the isBold property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsBold(String value) {
        this.isBold = value;
    }

    /**
     * Gets the value of the isItalic property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsItalic() {
        return isItalic;
    }

    /**
     * Sets the value of the isItalic property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsItalic(String value) {
        this.isItalic = value;
    }

    /**
     * Gets the value of the isUnderline property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsUnderline() {
        return isUnderline;
    }

    /**
     * Sets the value of the isUnderline property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsUnderline(String value) {
        this.isUnderline = value;
    }

    /**
     * Gets the value of the isStrikeThrough property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsStrikeThrough() {
        return isStrikeThrough;
    }

    /**
     * Sets the value of the isStrikeThrough property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsStrikeThrough(String value) {
        this.isStrikeThrough = value;
    }

    /**
     * Gets the value of the pdfFontName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPdfFontName() {
        return pdfFontName;
    }

    /**
     * Sets the value of the pdfFontName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPdfFontName(String value) {
        this.pdfFontName = value;
    }

    /**
     * Gets the value of the pdfEncoding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPdfEncoding() {
        return pdfEncoding;
    }

    /**
     * Sets the value of the pdfEncoding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPdfEncoding(String value) {
        this.pdfEncoding = value;
    }

    /**
     * Gets the value of the isPdfEmbedded property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsPdfEmbedded() {
        return isPdfEmbedded;
    }

    /**
     * Sets the value of the isPdfEmbedded property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsPdfEmbedded(String value) {
        this.isPdfEmbedded = value;
    }

    /**
     * Gets the value of the pattern property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPattern(String value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the isBlankWhenNull property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsBlankWhenNull() {
        return isBlankWhenNull;
    }

    /**
     * Sets the value of the isBlankWhenNull property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsBlankWhenNull(String value) {
        this.isBlankWhenNull = value;
    }

}
