//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package net.digistar.vanadio.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}variableDescription" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}variableExpression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}initialValueExpression" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" default="java.lang.String" /&gt;
 *       &lt;attribute name="resetType" default="Report"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="None"/&gt;
 *             &lt;enumeration value="Report"/&gt;
 *             &lt;enumeration value="Page"/&gt;
 *             &lt;enumeration value="Column"/&gt;
 *             &lt;enumeration value="Group"/&gt;
 *             &lt;enumeration value="Master"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="resetGroup" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="incrementType" default="None"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="None"/&gt;
 *             &lt;enumeration value="Report"/&gt;
 *             &lt;enumeration value="Page"/&gt;
 *             &lt;enumeration value="Column"/&gt;
 *             &lt;enumeration value="Group"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="incrementGroup" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="calculation" default="Nothing"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Nothing"/&gt;
 *             &lt;enumeration value="Count"/&gt;
 *             &lt;enumeration value="DistinctCount"/&gt;
 *             &lt;enumeration value="Sum"/&gt;
 *             &lt;enumeration value="Average"/&gt;
 *             &lt;enumeration value="Lowest"/&gt;
 *             &lt;enumeration value="Highest"/&gt;
 *             &lt;enumeration value="StandardDeviation"/&gt;
 *             &lt;enumeration value="Variance"/&gt;
 *             &lt;enumeration value="System"/&gt;
 *             &lt;enumeration value="First"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="incrementerFactoryClass" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "variableDescription",
        "variableExpression",
        "initialValueExpression"
})
@XmlRootElement(name = "variable", namespace = "http://jasperreports.sourceforge.net/jasperreports")
//@BindType
public class Variable {

    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected VariableDescription variableDescription;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected VariableExpression variableExpression;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected InitialValueExpression initialValueExpression;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute(name = "resetType")
    protected String resetType;
    @XmlAttribute(name = "resetGroup")
    protected String resetGroup;
    @XmlAttribute(name = "incrementType")
    protected String incrementType;
    @XmlAttribute(name = "incrementGroup")
    protected String incrementGroup;
    @XmlAttribute(name = "calculation")
    protected String calculation;
    @XmlAttribute(name = "incrementerFactoryClass")
    protected String incrementerFactoryClass;

    /**
     * Gets the value of the variableDescription property.
     *
     * @return possible object is
     * {@link VariableDescription }
     */
    public VariableDescription getVariableDescription() {
        return variableDescription;
    }

    /**
     * Sets the value of the variableDescription property.
     *
     * @param value allowed object is
     *              {@link VariableDescription }
     */
    public void setVariableDescription(VariableDescription value) {
        this.variableDescription = value;
    }

    /**
     * Gets the value of the variableExpression property.
     *
     * @return possible object is
     * {@link VariableExpression }
     */
    public VariableExpression getVariableExpression() {
        return variableExpression;
    }

    /**
     * Sets the value of the variableExpression property.
     *
     * @param value allowed object is
     *              {@link VariableExpression }
     */
    public void setVariableExpression(VariableExpression value) {
        this.variableExpression = value;
    }

    /**
     * Gets the value of the initialValueExpression property.
     *
     * @return possible object is
     * {@link InitialValueExpression }
     */
    public InitialValueExpression getInitialValueExpression() {
        return initialValueExpression;
    }

    /**
     * Sets the value of the initialValueExpression property.
     *
     * @param value allowed object is
     *              {@link InitialValueExpression }
     */
    public void setInitialValueExpression(InitialValueExpression value) {
        this.initialValueExpression = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clazz property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClazz() {
        if (clazz == null) {
            return "java.lang.String";
        } else {
            return clazz;
        }
    }

    /**
     * Sets the value of the clazz property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the resetType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResetType() {
        if (resetType == null) {
            return "Report";
        } else {
            return resetType;
        }
    }

    /**
     * Sets the value of the resetType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResetType(String value) {
        this.resetType = value;
    }

    /**
     * Gets the value of the resetGroup property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResetGroup() {
        return resetGroup;
    }

    /**
     * Sets the value of the resetGroup property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResetGroup(String value) {
        this.resetGroup = value;
    }

    /**
     * Gets the value of the incrementType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIncrementType() {
        if (incrementType == null) {
            return "None";
        } else {
            return incrementType;
        }
    }

    /**
     * Sets the value of the incrementType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIncrementType(String value) {
        this.incrementType = value;
    }

    /**
     * Gets the value of the incrementGroup property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIncrementGroup() {
        return incrementGroup;
    }

    /**
     * Sets the value of the incrementGroup property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIncrementGroup(String value) {
        this.incrementGroup = value;
    }

    /**
     * Gets the value of the calculation property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCalculation() {
        if (calculation == null) {
            return "Nothing";
        } else {
            return calculation;
        }
    }

    /**
     * Sets the value of the calculation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCalculation(String value) {
        this.calculation = value;
    }

    /**
     * Gets the value of the incrementerFactoryClass property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIncrementerFactoryClass() {
        return incrementerFactoryClass;
    }

    /**
     * Sets the value of the incrementerFactoryClass property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIncrementerFactoryClass(String value) {
        this.incrementerFactoryClass = value;
    }

}
