//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package net.digistar.vanadio.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;



/**
 * <p>Java class for variableReturnValue complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="variableReturnValue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://jasperreports.sourceforge.net/jasperreports}commonReturnValue"&gt;
 *       &lt;attribute name="fromVariable" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
// @XmlAccessorType(XmlAccessType.FIELD)

import com.abubusoft.kripton.annotation.BindType;
import com.abubusoft.kripton.annotation.BindXml;
import com.abubusoft.kripton.xml.XmlType;

@BindType
public class  VariableReturnValue
        extends CommonReturnValue {

    @BindXml(xmlType = XmlType.ATTRIBUTE) // name = "fromVariable")
    public String fromVariable;

    /**
     * Gets the value of the fromVariable property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFromVariable() {
        return fromVariable;
    }

    /**
     * Sets the value of the fromVariable property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFromVariable(String value) {
        this.fromVariable = value;
    }

}
