//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package net.digistar.vanadio.core.jasper;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexEvaluationTime.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="complexEvaluationTime"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Now"/&gt;
 *     &lt;enumeration value="Report"/&gt;
 *     &lt;enumeration value="Page"/&gt;
 *     &lt;enumeration value="Column"/&gt;
 *     &lt;enumeration value="Group"/&gt;
 *     &lt;enumeration value="Band"/&gt;
 *     &lt;enumeration value="Auto"/&gt;
 *     &lt;enumeration value="Master"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "complexEvaluationTime", namespace = "http://jasperreports.sourceforge.net/jasperreports")
@XmlEnum
public enum ComplexEvaluationTime {

    @XmlEnumValue("Now")
    NOW("Now"),
    @XmlEnumValue("Report")
    REPORT("Report"),
    @XmlEnumValue("Page")
    PAGE("Page"),
    @XmlEnumValue("Column")
    COLUMN("Column"),
    @XmlEnumValue("Group")
    GROUP("Group"),
    @XmlEnumValue("Band")
    BAND("Band"),
    @XmlEnumValue("Auto")
    AUTO("Auto"),
    @XmlEnumValue("Master")
    MASTER("Master");
    private final String value;

    ComplexEvaluationTime(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComplexEvaluationTime fromValue(String v) {
        for (ComplexEvaluationTime c: ComplexEvaluationTime.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
