//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package net.digistar.vanadio.core.jasper;

import com.abubusoft.kripton.annotation.BindXmlType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}datasetParameterExpression" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datasetParameterExpression"
})
@XmlRootElement(name = "datasetParameter", namespace = "http://jasperreports.sourceforge.net/jasperreports")
@BindXmlType
public class DatasetParameter {

    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected DatasetParameterExpression datasetParameterExpression;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the datasetParameterExpression property.
     * 
     * @return
     *     possible object is
     *     {@link DatasetParameterExpression }
     *     
     */
    public DatasetParameterExpression getDatasetParameterExpression() {
        return datasetParameterExpression;
    }

    /**
     * Sets the value of the datasetParameterExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatasetParameterExpression }
     *     
     */
    public void setDatasetParameterExpression(DatasetParameterExpression value) {
        this.datasetParameterExpression = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
