//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package net.digistar.vanadio.core.jasper;

import com.abubusoft.kripton.annotation.BindType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}seriesExpression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}taskExpression"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}subtaskExpression"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}startDateExpression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}endDateExpression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}percentExpression" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seriesExpression",
    "taskExpression",
    "subtaskExpression",
    "startDateExpression",
    "endDateExpression",
    "percentExpression"
})
@XmlRootElement(name = "ganttSeries", namespace = "http://jasperreports.sourceforge.net/jasperreports")
@BindType
public class GanttSeries {

    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected SeriesExpression seriesExpression;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports", required = true)
    protected TaskExpression taskExpression;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports", required = true)
    protected SubtaskExpression subtaskExpression;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected StartDateExpression startDateExpression;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected EndDateExpression endDateExpression;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected PercentExpression percentExpression;

    /**
     * Gets the value of the seriesExpression property.
     * 
     * @return
     *     possible object is
     *     {@link SeriesExpression }
     *     
     */
    public SeriesExpression getSeriesExpression() {
        return seriesExpression;
    }

    /**
     * Sets the value of the seriesExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeriesExpression }
     *     
     */
    public void setSeriesExpression(SeriesExpression value) {
        this.seriesExpression = value;
    }

    /**
     * Gets the value of the taskExpression property.
     * 
     * @return
     *     possible object is
     *     {@link TaskExpression }
     *     
     */
    public TaskExpression getTaskExpression() {
        return taskExpression;
    }

    /**
     * Sets the value of the taskExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskExpression }
     *     
     */
    public void setTaskExpression(TaskExpression value) {
        this.taskExpression = value;
    }

    /**
     * Gets the value of the subtaskExpression property.
     * 
     * @return
     *     possible object is
     *     {@link SubtaskExpression }
     *     
     */
    public SubtaskExpression getSubtaskExpression() {
        return subtaskExpression;
    }

    /**
     * Sets the value of the subtaskExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubtaskExpression }
     *     
     */
    public void setSubtaskExpression(SubtaskExpression value) {
        this.subtaskExpression = value;
    }

    /**
     * Gets the value of the startDateExpression property.
     * 
     * @return
     *     possible object is
     *     {@link StartDateExpression }
     *     
     */
    public StartDateExpression getStartDateExpression() {
        return startDateExpression;
    }

    /**
     * Sets the value of the startDateExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartDateExpression }
     *     
     */
    public void setStartDateExpression(StartDateExpression value) {
        this.startDateExpression = value;
    }

    /**
     * Gets the value of the endDateExpression property.
     * 
     * @return
     *     possible object is
     *     {@link EndDateExpression }
     *     
     */
    public EndDateExpression getEndDateExpression() {
        return endDateExpression;
    }

    /**
     * Sets the value of the endDateExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndDateExpression }
     *     
     */
    public void setEndDateExpression(EndDateExpression value) {
        this.endDateExpression = value;
    }

    /**
     * Gets the value of the percentExpression property.
     * 
     * @return
     *     possible object is
     *     {@link PercentExpression }
     *     
     */
    public PercentExpression getPercentExpression() {
        return percentExpression;
    }

    /**
     * Sets the value of the percentExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentExpression }
     *     
     */
    public void setPercentExpression(PercentExpression value) {
        this.percentExpression = value;
    }

}
