//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package jasper;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}reportElement"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}box" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}crosstabParameter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}parametersMapExpression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}crosstabDataset" minOccurs="0"/&gt;
 *         &lt;element name="titleCell" type="{http://jasperreports.sourceforge.net/jasperreports}CrosstabColumnCell" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}crosstabHeaderCell" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}rowGroup" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}columnGroup" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}measure" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}crosstabCell" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}whenNoDataCell" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="isRepeatColumnHeaders" default="true"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="isRepeatRowHeaders" default="true"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="columnBreakOffset" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="10" /&gt;
 *       &lt;attribute name="runDirection" default="LTR"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="LTR"/&gt;
 *             &lt;enumeration value="RTL"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ignoreWidth" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="horizontalPosition"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Left"/&gt;
 *             &lt;enumeration value="Right"/&gt;
 *             &lt;enumeration value="Center"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reportElement",
    "box",
    "crosstabParameter",
    "parametersMapExpression",
    "crosstabDataset",
    "titleCell",
    "crosstabHeaderCell",
    "rowGroup",
    "columnGroup",
    "measure",
    "crosstabCell",
    "whenNoDataCell"
})
@XmlRootElement(name = "crosstab", namespace = "http://jasperreports.sourceforge.net/jasperreports")
public class Crosstab {

    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports", required = true)
    protected ReportElement reportElement;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected Box box;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected List<CrosstabParameter> crosstabParameter;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected ParametersMapExpression parametersMapExpression;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected CrosstabDataset crosstabDataset;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected CrosstabColumnCell titleCell;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected CrosstabHeaderCell crosstabHeaderCell;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected List<RowGroup> rowGroup;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected List<ColumnGroup> columnGroup;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected List<Measure> measure;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected List<CrosstabCell> crosstabCell;
    @XmlElement(namespace = "http://jasperreports.sourceforge.net/jasperreports")
    protected WhenNoDataCell whenNoDataCell;
    @XmlAttribute(name = "isRepeatColumnHeaders")
    protected String isRepeatColumnHeaders;
    @XmlAttribute(name = "isRepeatRowHeaders")
    protected String isRepeatRowHeaders;
    @XmlAttribute(name = "columnBreakOffset")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String columnBreakOffset;
    @XmlAttribute(name = "runDirection")
    protected String runDirection;
    @XmlAttribute(name = "ignoreWidth")
    protected Boolean ignoreWidth;
    @XmlAttribute(name = "horizontalPosition")
    protected String horizontalPosition;

    /**
     * Gets the value of the reportElement property.
     * 
     * @return
     *     possible object is
     *     {@link ReportElement }
     *     
     */
    public ReportElement getReportElement() {
        return reportElement;
    }

    /**
     * Sets the value of the reportElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportElement }
     *     
     */
    public void setReportElement(ReportElement value) {
        this.reportElement = value;
    }

    /**
     * Gets the value of the box property.
     * 
     * @return
     *     possible object is
     *     {@link Box }
     *     
     */
    public Box getBox() {
        return box;
    }

    /**
     * Sets the value of the box property.
     * 
     * @param value
     *     allowed object is
     *     {@link Box }
     *     
     */
    public void setBox(Box value) {
        this.box = value;
    }

    /**
     * Gets the value of the crosstabParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crosstabParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrosstabParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CrosstabParameter }
     * 
     * 
     */
    public List<CrosstabParameter> getCrosstabParameter() {
        if (crosstabParameter == null) {
            crosstabParameter = new ArrayList<CrosstabParameter>();
        }
        return this.crosstabParameter;
    }

    /**
     * Gets the value of the parametersMapExpression property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersMapExpression }
     *     
     */
    public ParametersMapExpression getParametersMapExpression() {
        return parametersMapExpression;
    }

    /**
     * Sets the value of the parametersMapExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersMapExpression }
     *     
     */
    public void setParametersMapExpression(ParametersMapExpression value) {
        this.parametersMapExpression = value;
    }

    /**
     * Gets the value of the crosstabDataset property.
     * 
     * @return
     *     possible object is
     *     {@link CrosstabDataset }
     *     
     */
    public CrosstabDataset getCrosstabDataset() {
        return crosstabDataset;
    }

    /**
     * Sets the value of the crosstabDataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrosstabDataset }
     *     
     */
    public void setCrosstabDataset(CrosstabDataset value) {
        this.crosstabDataset = value;
    }

    /**
     * Gets the value of the titleCell property.
     * 
     * @return
     *     possible object is
     *     {@link CrosstabColumnCell }
     *     
     */
    public CrosstabColumnCell getTitleCell() {
        return titleCell;
    }

    /**
     * Sets the value of the titleCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrosstabColumnCell }
     *     
     */
    public void setTitleCell(CrosstabColumnCell value) {
        this.titleCell = value;
    }

    /**
     * Gets the value of the crosstabHeaderCell property.
     * 
     * @return
     *     possible object is
     *     {@link CrosstabHeaderCell }
     *     
     */
    public CrosstabHeaderCell getCrosstabHeaderCell() {
        return crosstabHeaderCell;
    }

    /**
     * Sets the value of the crosstabHeaderCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrosstabHeaderCell }
     *     
     */
    public void setCrosstabHeaderCell(CrosstabHeaderCell value) {
        this.crosstabHeaderCell = value;
    }

    /**
     * Gets the value of the rowGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rowGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRowGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RowGroup }
     * 
     * 
     */
    public List<RowGroup> getRowGroup() {
        if (rowGroup == null) {
            rowGroup = new ArrayList<RowGroup>();
        }
        return this.rowGroup;
    }

    /**
     * Gets the value of the columnGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columnGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumnGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColumnGroup }
     * 
     * 
     */
    public List<ColumnGroup> getColumnGroup() {
        if (columnGroup == null) {
            columnGroup = new ArrayList<ColumnGroup>();
        }
        return this.columnGroup;
    }

    /**
     * Gets the value of the measure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Measure }
     * 
     * 
     */
    public List<Measure> getMeasure() {
        if (measure == null) {
            measure = new ArrayList<Measure>();
        }
        return this.measure;
    }

    /**
     * Gets the value of the crosstabCell property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crosstabCell property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrosstabCell().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CrosstabCell }
     * 
     * 
     */
    public List<CrosstabCell> getCrosstabCell() {
        if (crosstabCell == null) {
            crosstabCell = new ArrayList<CrosstabCell>();
        }
        return this.crosstabCell;
    }

    /**
     * Gets the value of the whenNoDataCell property.
     * 
     * @return
     *     possible object is
     *     {@link WhenNoDataCell }
     *     
     */
    public WhenNoDataCell getWhenNoDataCell() {
        return whenNoDataCell;
    }

    /**
     * Sets the value of the whenNoDataCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhenNoDataCell }
     *     
     */
    public void setWhenNoDataCell(WhenNoDataCell value) {
        this.whenNoDataCell = value;
    }

    /**
     * Gets the value of the isRepeatColumnHeaders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsRepeatColumnHeaders() {
        if (isRepeatColumnHeaders == null) {
            return "true";
        } else {
            return isRepeatColumnHeaders;
        }
    }

    /**
     * Sets the value of the isRepeatColumnHeaders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsRepeatColumnHeaders(String value) {
        this.isRepeatColumnHeaders = value;
    }

    /**
     * Gets the value of the isRepeatRowHeaders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsRepeatRowHeaders() {
        if (isRepeatRowHeaders == null) {
            return "true";
        } else {
            return isRepeatRowHeaders;
        }
    }

    /**
     * Sets the value of the isRepeatRowHeaders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsRepeatRowHeaders(String value) {
        this.isRepeatRowHeaders = value;
    }

    /**
     * Gets the value of the columnBreakOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnBreakOffset() {
        if (columnBreakOffset == null) {
            return "10";
        } else {
            return columnBreakOffset;
        }
    }

    /**
     * Sets the value of the columnBreakOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnBreakOffset(String value) {
        this.columnBreakOffset = value;
    }

    /**
     * Gets the value of the runDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunDirection() {
        if (runDirection == null) {
            return "LTR";
        } else {
            return runDirection;
        }
    }

    /**
     * Sets the value of the runDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunDirection(String value) {
        this.runDirection = value;
    }

    /**
     * Gets the value of the ignoreWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIgnoreWidth() {
        return ignoreWidth;
    }

    /**
     * Sets the value of the ignoreWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIgnoreWidth(Boolean value) {
        this.ignoreWidth = value;
    }

    /**
     * Gets the value of the horizontalPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorizontalPosition() {
        return horizontalPosition;
    }

    /**
     * Sets the value of the horizontalPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorizontalPosition(String value) {
        this.horizontalPosition = value;
    }

}
