//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 11:06:40 PM CEST 
//


package jasper;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.digitstar.vanadio.core.jasper package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PropertyExpression_QNAME = new QName("http://jasperreports.sourceforge.net/jasperreports", "propertyExpression");
    private final static QName _PatternExpression_QNAME = new QName("http://jasperreports.sourceforge.net/jasperreports", "patternExpression");
    private final static QName _Component_QNAME = new QName("http://jasperreports.sourceforge.net/jasperreports", "component");
    private final static QName _PartComponent_QNAME = new QName("http://jasperreports.sourceforge.net/jasperreports", "partComponent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.digitstar.vanadio.core.jasper
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenericElementParameter }
     * 
     */
    public GenericElementParameter createGenericElementParameter() {
        return new GenericElementParameter();
    }

    /**
     * Create an instance of {@link AxisLevel }
     * 
     */
    public AxisLevel createAxisLevel() {
        return new AxisLevel();
    }

    /**
     * Create an instance of {@link AxisLevelBucket }
     * 
     */
    public AxisLevelBucket createAxisLevelBucket() {
        return new AxisLevelBucket();
    }

    /**
     * Create an instance of {@link MultiAxisMeasure }
     * 
     */
    public MultiAxisMeasure createMultiAxisMeasure() {
        return new MultiAxisMeasure();
    }

    /**
     * Create an instance of {@link ExpressionReturnValue }
     * 
     */
    public ExpressionReturnValue createExpressionReturnValue() {
        return new ExpressionReturnValue();
    }

    /**
     * Create an instance of {@link JasperReport }
     * 
     */
    public JasperReport createJasperReport() {
        return new JasperReport();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link DatasetPropertyExpressionType }
     * 
     */
    public DatasetPropertyExpressionType createDatasetPropertyExpressionType() {
        return new DatasetPropertyExpressionType();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link Template }
     * 
     */
    public Template createTemplate() {
        return new Template();
    }

    /**
     * Create an instance of {@link ReportFont }
     * 
     */
    public ReportFont createReportFont() {
        return new ReportFont();
    }

    /**
     * Create an instance of {@link Style }
     * 
     */
    public Style createStyle() {
        return new Style();
    }

    /**
     * Create an instance of {@link Pen }
     * 
     */
    public Pen createPen() {
        return new Pen();
    }

    /**
     * Create an instance of {@link Box }
     * 
     */
    public Box createBox() {
        return new Box();
    }

    /**
     * Create an instance of {@link TopPen }
     * 
     */
    public TopPen createTopPen() {
        return new TopPen();
    }

    /**
     * Create an instance of {@link LeftPen }
     * 
     */
    public LeftPen createLeftPen() {
        return new LeftPen();
    }

    /**
     * Create an instance of {@link BottomPen }
     * 
     */
    public BottomPen createBottomPen() {
        return new BottomPen();
    }

    /**
     * Create an instance of {@link RightPen }
     * 
     */
    public RightPen createRightPen() {
        return new RightPen();
    }

    /**
     * Create an instance of {@link Paragraph }
     * 
     */
    public Paragraph createParagraph() {
        return new Paragraph();
    }

    /**
     * Create an instance of {@link TabStop }
     * 
     */
    public TabStop createTabStop() {
        return new TabStop();
    }

    /**
     * Create an instance of {@link ConditionalStyle }
     * 
     */
    public ConditionalStyle createConditionalStyle() {
        return new ConditionalStyle();
    }

    /**
     * Create an instance of {@link ConditionExpression }
     * 
     */
    public ConditionExpression createConditionExpression() {
        return new ConditionExpression();
    }

    /**
     * Create an instance of {@link SubDataset }
     * 
     */
    public SubDataset createSubDataset() {
        return new SubDataset();
    }

    /**
     * Create an instance of {@link Scriptlet }
     * 
     */
    public Scriptlet createScriptlet() {
        return new Scriptlet();
    }

    /**
     * Create an instance of {@link ScriptletDescription }
     * 
     */
    public ScriptletDescription createScriptletDescription() {
        return new ScriptletDescription();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link ParameterDescription }
     * 
     */
    public ParameterDescription createParameterDescription() {
        return new ParameterDescription();
    }

    /**
     * Create an instance of {@link DefaultValueExpression }
     * 
     */
    public DefaultValueExpression createDefaultValueExpression() {
        return new DefaultValueExpression();
    }

    /**
     * Create an instance of {@link QueryString }
     * 
     */
    public QueryString createQueryString() {
        return new QueryString();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link PropertyExpressionType }
     * 
     */
    public PropertyExpressionType createPropertyExpressionType() {
        return new PropertyExpressionType();
    }

    /**
     * Create an instance of {@link FieldDescription }
     * 
     */
    public FieldDescription createFieldDescription() {
        return new FieldDescription();
    }

    /**
     * Create an instance of {@link SortField }
     * 
     */
    public SortField createSortField() {
        return new SortField();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link VariableDescription }
     * 
     */
    public VariableDescription createVariableDescription() {
        return new VariableDescription();
    }

    /**
     * Create an instance of {@link VariableExpression }
     * 
     */
    public VariableExpression createVariableExpression() {
        return new VariableExpression();
    }

    /**
     * Create an instance of {@link InitialValueExpression }
     * 
     */
    public InitialValueExpression createInitialValueExpression() {
        return new InitialValueExpression();
    }

    /**
     * Create an instance of {@link FilterExpression }
     * 
     */
    public FilterExpression createFilterExpression() {
        return new FilterExpression();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link GroupExpression }
     * 
     */
    public GroupExpression createGroupExpression() {
        return new GroupExpression();
    }

    /**
     * Create an instance of {@link GroupHeader }
     * 
     */
    public GroupHeader createGroupHeader() {
        return new GroupHeader();
    }

    /**
     * Create an instance of {@link Band }
     * 
     */
    public Band createBand() {
        return new Band();
    }

    /**
     * Create an instance of {@link PrintWhenExpression }
     * 
     */
    public PrintWhenExpression createPrintWhenExpression() {
        return new PrintWhenExpression();
    }

    /**
     * Create an instance of {@link Break }
     * 
     */
    public Break createBreak() {
        return new Break();
    }

    /**
     * Create an instance of {@link ReportElement }
     * 
     */
    public ReportElement createReportElement() {
        return new ReportElement();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link GraphicElement }
     * 
     */
    public GraphicElement createGraphicElement() {
        return new GraphicElement();
    }

    /**
     * Create an instance of {@link Rectangle }
     * 
     */
    public Rectangle createRectangle() {
        return new Rectangle();
    }

    /**
     * Create an instance of {@link Ellipse }
     * 
     */
    public Ellipse createEllipse() {
        return new Ellipse();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link ImageExpression }
     * 
     */
    public ImageExpression createImageExpression() {
        return new ImageExpression();
    }

    /**
     * Create an instance of {@link AnchorNameExpression }
     * 
     */
    public AnchorNameExpression createAnchorNameExpression() {
        return new AnchorNameExpression();
    }

    /**
     * Create an instance of {@link HyperlinkReferenceExpression }
     * 
     */
    public HyperlinkReferenceExpression createHyperlinkReferenceExpression() {
        return new HyperlinkReferenceExpression();
    }

    /**
     * Create an instance of {@link HyperlinkWhenExpression }
     * 
     */
    public HyperlinkWhenExpression createHyperlinkWhenExpression() {
        return new HyperlinkWhenExpression();
    }

    /**
     * Create an instance of {@link HyperlinkAnchorExpression }
     * 
     */
    public HyperlinkAnchorExpression createHyperlinkAnchorExpression() {
        return new HyperlinkAnchorExpression();
    }

    /**
     * Create an instance of {@link HyperlinkPageExpression }
     * 
     */
    public HyperlinkPageExpression createHyperlinkPageExpression() {
        return new HyperlinkPageExpression();
    }

    /**
     * Create an instance of {@link HyperlinkTooltipExpression }
     * 
     */
    public HyperlinkTooltipExpression createHyperlinkTooltipExpression() {
        return new HyperlinkTooltipExpression();
    }

    /**
     * Create an instance of {@link HyperlinkParameter }
     * 
     */
    public HyperlinkParameter createHyperlinkParameter() {
        return new HyperlinkParameter();
    }

    /**
     * Create an instance of {@link HyperlinkParameterExpression }
     * 
     */
    public HyperlinkParameterExpression createHyperlinkParameterExpression() {
        return new HyperlinkParameterExpression();
    }

    /**
     * Create an instance of {@link StaticText }
     * 
     */
    public StaticText createStaticText() {
        return new StaticText();
    }

    /**
     * Create an instance of {@link TextElement }
     * 
     */
    public TextElement createTextElement() {
        return new TextElement();
    }

    /**
     * Create an instance of {@link Font }
     * 
     */
    public Font createFont() {
        return new Font();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link TextField }
     * 
     */
    public TextField createTextField() {
        return new TextField();
    }

    /**
     * Create an instance of {@link TextFieldExpression }
     * 
     */
    public TextFieldExpression createTextFieldExpression() {
        return new TextFieldExpression();
    }

    /**
     * Create an instance of {@link Subreport }
     * 
     */
    public Subreport createSubreport() {
        return new Subreport();
    }

    /**
     * Create an instance of {@link ParametersMapExpression }
     * 
     */
    public ParametersMapExpression createParametersMapExpression() {
        return new ParametersMapExpression();
    }

    /**
     * Create an instance of {@link SubreportParameter }
     * 
     */
    public SubreportParameter createSubreportParameter() {
        return new SubreportParameter();
    }

    /**
     * Create an instance of {@link SubreportParameterExpression }
     * 
     */
    public SubreportParameterExpression createSubreportParameterExpression() {
        return new SubreportParameterExpression();
    }

    /**
     * Create an instance of {@link ConnectionExpression }
     * 
     */
    public ConnectionExpression createConnectionExpression() {
        return new ConnectionExpression();
    }

    /**
     * Create an instance of {@link DataSourceExpression }
     * 
     */
    public DataSourceExpression createDataSourceExpression() {
        return new DataSourceExpression();
    }

    /**
     * Create an instance of {@link ReturnValue }
     * 
     */
    public ReturnValue createReturnValue() {
        return new ReturnValue();
    }

    /**
     * Create an instance of {@link SubreportExpression }
     * 
     */
    public SubreportExpression createSubreportExpression() {
        return new SubreportExpression();
    }

    /**
     * Create an instance of {@link PieChart }
     * 
     */
    public PieChart createPieChart() {
        return new PieChart();
    }

    /**
     * Create an instance of {@link Chart }
     * 
     */
    public Chart createChart() {
        return new Chart();
    }

    /**
     * Create an instance of {@link ChartTitle }
     * 
     */
    public ChartTitle createChartTitle() {
        return new ChartTitle();
    }

    /**
     * Create an instance of {@link TitleExpression }
     * 
     */
    public TitleExpression createTitleExpression() {
        return new TitleExpression();
    }

    /**
     * Create an instance of {@link ChartSubtitle }
     * 
     */
    public ChartSubtitle createChartSubtitle() {
        return new ChartSubtitle();
    }

    /**
     * Create an instance of {@link SubtitleExpression }
     * 
     */
    public SubtitleExpression createSubtitleExpression() {
        return new SubtitleExpression();
    }

    /**
     * Create an instance of {@link ChartLegend }
     * 
     */
    public ChartLegend createChartLegend() {
        return new ChartLegend();
    }

    /**
     * Create an instance of {@link PieDataset }
     * 
     */
    public PieDataset createPieDataset() {
        return new PieDataset();
    }

    /**
     * Create an instance of {@link Dataset }
     * 
     */
    public Dataset createDataset() {
        return new Dataset();
    }

    /**
     * Create an instance of {@link IncrementWhenExpression }
     * 
     */
    public IncrementWhenExpression createIncrementWhenExpression() {
        return new IncrementWhenExpression();
    }

    /**
     * Create an instance of {@link DatasetRun }
     * 
     */
    public DatasetRun createDatasetRun() {
        return new DatasetRun();
    }

    /**
     * Create an instance of {@link DatasetParameter }
     * 
     */
    public DatasetParameter createDatasetParameter() {
        return new DatasetParameter();
    }

    /**
     * Create an instance of {@link DatasetParameterExpression }
     * 
     */
    public DatasetParameterExpression createDatasetParameterExpression() {
        return new DatasetParameterExpression();
    }

    /**
     * Create an instance of {@link VariableReturnValue }
     * 
     */
    public VariableReturnValue createVariableReturnValue() {
        return new VariableReturnValue();
    }

    /**
     * Create an instance of {@link PieSeries }
     * 
     */
    public PieSeries createPieSeries() {
        return new PieSeries();
    }

    /**
     * Create an instance of {@link KeyExpression }
     * 
     */
    public KeyExpression createKeyExpression() {
        return new KeyExpression();
    }

    /**
     * Create an instance of {@link ValueExpression }
     * 
     */
    public ValueExpression createValueExpression() {
        return new ValueExpression();
    }

    /**
     * Create an instance of {@link LabelExpression }
     * 
     */
    public LabelExpression createLabelExpression() {
        return new LabelExpression();
    }

    /**
     * Create an instance of {@link SectionHyperlink }
     * 
     */
    public SectionHyperlink createSectionHyperlink() {
        return new SectionHyperlink();
    }

    /**
     * Create an instance of {@link OtherKeyExpression }
     * 
     */
    public OtherKeyExpression createOtherKeyExpression() {
        return new OtherKeyExpression();
    }

    /**
     * Create an instance of {@link OtherLabelExpression }
     * 
     */
    public OtherLabelExpression createOtherLabelExpression() {
        return new OtherLabelExpression();
    }

    /**
     * Create an instance of {@link OtherSectionHyperlink }
     * 
     */
    public OtherSectionHyperlink createOtherSectionHyperlink() {
        return new OtherSectionHyperlink();
    }

    /**
     * Create an instance of {@link PiePlot }
     * 
     */
    public PiePlot createPiePlot() {
        return new PiePlot();
    }

    /**
     * Create an instance of {@link Plot }
     * 
     */
    public Plot createPlot() {
        return new Plot();
    }

    /**
     * Create an instance of {@link SeriesColor }
     * 
     */
    public SeriesColor createSeriesColor() {
        return new SeriesColor();
    }

    /**
     * Create an instance of {@link ItemLabel }
     * 
     */
    public ItemLabel createItemLabel() {
        return new ItemLabel();
    }

    /**
     * Create an instance of {@link Pie3DChart }
     * 
     */
    public Pie3DChart createPie3DChart() {
        return new Pie3DChart();
    }

    /**
     * Create an instance of {@link Pie3DPlot }
     * 
     */
    public Pie3DPlot createPie3DPlot() {
        return new Pie3DPlot();
    }

    /**
     * Create an instance of {@link BarChart }
     * 
     */
    public BarChart createBarChart() {
        return new BarChart();
    }

    /**
     * Create an instance of {@link CategoryDataset }
     * 
     */
    public CategoryDataset createCategoryDataset() {
        return new CategoryDataset();
    }

    /**
     * Create an instance of {@link CategorySeries }
     * 
     */
    public CategorySeries createCategorySeries() {
        return new CategorySeries();
    }

    /**
     * Create an instance of {@link SeriesExpression }
     * 
     */
    public SeriesExpression createSeriesExpression() {
        return new SeriesExpression();
    }

    /**
     * Create an instance of {@link CategoryExpression }
     * 
     */
    public CategoryExpression createCategoryExpression() {
        return new CategoryExpression();
    }

    /**
     * Create an instance of {@link ItemHyperlink }
     * 
     */
    public ItemHyperlink createItemHyperlink() {
        return new ItemHyperlink();
    }

    /**
     * Create an instance of {@link BarPlot }
     * 
     */
    public BarPlot createBarPlot() {
        return new BarPlot();
    }

    /**
     * Create an instance of {@link CategoryAxisLabelExpression }
     * 
     */
    public CategoryAxisLabelExpression createCategoryAxisLabelExpression() {
        return new CategoryAxisLabelExpression();
    }

    /**
     * Create an instance of {@link CategoryAxisFormat }
     * 
     */
    public CategoryAxisFormat createCategoryAxisFormat() {
        return new CategoryAxisFormat();
    }

    /**
     * Create an instance of {@link AxisFormat }
     * 
     */
    public AxisFormat createAxisFormat() {
        return new AxisFormat();
    }

    /**
     * Create an instance of {@link LabelFont }
     * 
     */
    public LabelFont createLabelFont() {
        return new LabelFont();
    }

    /**
     * Create an instance of {@link TickLabelFont }
     * 
     */
    public TickLabelFont createTickLabelFont() {
        return new TickLabelFont();
    }

    /**
     * Create an instance of {@link ValueAxisLabelExpression }
     * 
     */
    public ValueAxisLabelExpression createValueAxisLabelExpression() {
        return new ValueAxisLabelExpression();
    }

    /**
     * Create an instance of {@link ValueAxisFormat }
     * 
     */
    public ValueAxisFormat createValueAxisFormat() {
        return new ValueAxisFormat();
    }

    /**
     * Create an instance of {@link DomainAxisMinValueExpression }
     * 
     */
    public DomainAxisMinValueExpression createDomainAxisMinValueExpression() {
        return new DomainAxisMinValueExpression();
    }

    /**
     * Create an instance of {@link DomainAxisMaxValueExpression }
     * 
     */
    public DomainAxisMaxValueExpression createDomainAxisMaxValueExpression() {
        return new DomainAxisMaxValueExpression();
    }

    /**
     * Create an instance of {@link RangeAxisMinValueExpression }
     * 
     */
    public RangeAxisMinValueExpression createRangeAxisMinValueExpression() {
        return new RangeAxisMinValueExpression();
    }

    /**
     * Create an instance of {@link RangeAxisMaxValueExpression }
     * 
     */
    public RangeAxisMaxValueExpression createRangeAxisMaxValueExpression() {
        return new RangeAxisMaxValueExpression();
    }

    /**
     * Create an instance of {@link Bar3DChart }
     * 
     */
    public Bar3DChart createBar3DChart() {
        return new Bar3DChart();
    }

    /**
     * Create an instance of {@link Bar3DPlot }
     * 
     */
    public Bar3DPlot createBar3DPlot() {
        return new Bar3DPlot();
    }

    /**
     * Create an instance of {@link XyBarChart }
     * 
     */
    public XyBarChart createXyBarChart() {
        return new XyBarChart();
    }

    /**
     * Create an instance of {@link TimePeriodDataset }
     * 
     */
    public TimePeriodDataset createTimePeriodDataset() {
        return new TimePeriodDataset();
    }

    /**
     * Create an instance of {@link TimePeriodSeries }
     * 
     */
    public TimePeriodSeries createTimePeriodSeries() {
        return new TimePeriodSeries();
    }

    /**
     * Create an instance of {@link StartDateExpression }
     * 
     */
    public StartDateExpression createStartDateExpression() {
        return new StartDateExpression();
    }

    /**
     * Create an instance of {@link EndDateExpression }
     * 
     */
    public EndDateExpression createEndDateExpression() {
        return new EndDateExpression();
    }

    /**
     * Create an instance of {@link TimeSeriesDataset }
     * 
     */
    public TimeSeriesDataset createTimeSeriesDataset() {
        return new TimeSeriesDataset();
    }

    /**
     * Create an instance of {@link TimeSeries }
     * 
     */
    public TimeSeries createTimeSeries() {
        return new TimeSeries();
    }

    /**
     * Create an instance of {@link TimePeriodExpression }
     * 
     */
    public TimePeriodExpression createTimePeriodExpression() {
        return new TimePeriodExpression();
    }

    /**
     * Create an instance of {@link XyDataset }
     * 
     */
    public XyDataset createXyDataset() {
        return new XyDataset();
    }

    /**
     * Create an instance of {@link XySeries }
     * 
     */
    public XySeries createXySeries() {
        return new XySeries();
    }

    /**
     * Create an instance of {@link XValueExpression }
     * 
     */
    public XValueExpression createXValueExpression() {
        return new XValueExpression();
    }

    /**
     * Create an instance of {@link YValueExpression }
     * 
     */
    public YValueExpression createYValueExpression() {
        return new YValueExpression();
    }

    /**
     * Create an instance of {@link StackedBarChart }
     * 
     */
    public StackedBarChart createStackedBarChart() {
        return new StackedBarChart();
    }

    /**
     * Create an instance of {@link StackedBar3DChart }
     * 
     */
    public StackedBar3DChart createStackedBar3DChart() {
        return new StackedBar3DChart();
    }

    /**
     * Create an instance of {@link LineChart }
     * 
     */
    public LineChart createLineChart() {
        return new LineChart();
    }

    /**
     * Create an instance of {@link LinePlot }
     * 
     */
    public LinePlot createLinePlot() {
        return new LinePlot();
    }

    /**
     * Create an instance of {@link XyLineChart }
     * 
     */
    public XyLineChart createXyLineChart() {
        return new XyLineChart();
    }

    /**
     * Create an instance of {@link AreaChart }
     * 
     */
    public AreaChart createAreaChart() {
        return new AreaChart();
    }

    /**
     * Create an instance of {@link AreaPlot }
     * 
     */
    public AreaPlot createAreaPlot() {
        return new AreaPlot();
    }

    /**
     * Create an instance of {@link XyAreaChart }
     * 
     */
    public XyAreaChart createXyAreaChart() {
        return new XyAreaChart();
    }

    /**
     * Create an instance of {@link ScatterChart }
     * 
     */
    public ScatterChart createScatterChart() {
        return new ScatterChart();
    }

    /**
     * Create an instance of {@link ScatterPlot }
     * 
     */
    public ScatterPlot createScatterPlot() {
        return new ScatterPlot();
    }

    /**
     * Create an instance of {@link XAxisLabelExpression }
     * 
     */
    public XAxisLabelExpression createXAxisLabelExpression() {
        return new XAxisLabelExpression();
    }

    /**
     * Create an instance of {@link XAxisFormat }
     * 
     */
    public XAxisFormat createXAxisFormat() {
        return new XAxisFormat();
    }

    /**
     * Create an instance of {@link YAxisLabelExpression }
     * 
     */
    public YAxisLabelExpression createYAxisLabelExpression() {
        return new YAxisLabelExpression();
    }

    /**
     * Create an instance of {@link YAxisFormat }
     * 
     */
    public YAxisFormat createYAxisFormat() {
        return new YAxisFormat();
    }

    /**
     * Create an instance of {@link BubbleChart }
     * 
     */
    public BubbleChart createBubbleChart() {
        return new BubbleChart();
    }

    /**
     * Create an instance of {@link XyzDataset }
     * 
     */
    public XyzDataset createXyzDataset() {
        return new XyzDataset();
    }

    /**
     * Create an instance of {@link XyzSeries }
     * 
     */
    public XyzSeries createXyzSeries() {
        return new XyzSeries();
    }

    /**
     * Create an instance of {@link ZValueExpression }
     * 
     */
    public ZValueExpression createZValueExpression() {
        return new ZValueExpression();
    }

    /**
     * Create an instance of {@link BubblePlot }
     * 
     */
    public BubblePlot createBubblePlot() {
        return new BubblePlot();
    }

    /**
     * Create an instance of {@link TimeSeriesChart }
     * 
     */
    public TimeSeriesChart createTimeSeriesChart() {
        return new TimeSeriesChart();
    }

    /**
     * Create an instance of {@link TimeSeriesPlot }
     * 
     */
    public TimeSeriesPlot createTimeSeriesPlot() {
        return new TimeSeriesPlot();
    }

    /**
     * Create an instance of {@link TimeAxisLabelExpression }
     * 
     */
    public TimeAxisLabelExpression createTimeAxisLabelExpression() {
        return new TimeAxisLabelExpression();
    }

    /**
     * Create an instance of {@link TimeAxisFormat }
     * 
     */
    public TimeAxisFormat createTimeAxisFormat() {
        return new TimeAxisFormat();
    }

    /**
     * Create an instance of {@link HighLowChart }
     * 
     */
    public HighLowChart createHighLowChart() {
        return new HighLowChart();
    }

    /**
     * Create an instance of {@link HighLowDataset }
     * 
     */
    public HighLowDataset createHighLowDataset() {
        return new HighLowDataset();
    }

    /**
     * Create an instance of {@link DateExpression }
     * 
     */
    public DateExpression createDateExpression() {
        return new DateExpression();
    }

    /**
     * Create an instance of {@link HighExpression }
     * 
     */
    public HighExpression createHighExpression() {
        return new HighExpression();
    }

    /**
     * Create an instance of {@link LowExpression }
     * 
     */
    public LowExpression createLowExpression() {
        return new LowExpression();
    }

    /**
     * Create an instance of {@link OpenExpression }
     * 
     */
    public OpenExpression createOpenExpression() {
        return new OpenExpression();
    }

    /**
     * Create an instance of {@link CloseExpression }
     * 
     */
    public CloseExpression createCloseExpression() {
        return new CloseExpression();
    }

    /**
     * Create an instance of {@link VolumeExpression }
     * 
     */
    public VolumeExpression createVolumeExpression() {
        return new VolumeExpression();
    }

    /**
     * Create an instance of {@link HighLowPlot }
     * 
     */
    public HighLowPlot createHighLowPlot() {
        return new HighLowPlot();
    }

    /**
     * Create an instance of {@link CandlestickChart }
     * 
     */
    public CandlestickChart createCandlestickChart() {
        return new CandlestickChart();
    }

    /**
     * Create an instance of {@link CandlestickPlot }
     * 
     */
    public CandlestickPlot createCandlestickPlot() {
        return new CandlestickPlot();
    }

    /**
     * Create an instance of {@link MeterChart }
     * 
     */
    public MeterChart createMeterChart() {
        return new MeterChart();
    }

    /**
     * Create an instance of {@link ValueDataset }
     * 
     */
    public ValueDataset createValueDataset() {
        return new ValueDataset();
    }

    /**
     * Create an instance of {@link MeterPlot }
     * 
     */
    public MeterPlot createMeterPlot() {
        return new MeterPlot();
    }

    /**
     * Create an instance of {@link ValueDisplay }
     * 
     */
    public ValueDisplay createValueDisplay() {
        return new ValueDisplay();
    }

    /**
     * Create an instance of {@link DataRange }
     * 
     */
    public DataRange createDataRange() {
        return new DataRange();
    }

    /**
     * Create an instance of {@link MeterInterval }
     * 
     */
    public MeterInterval createMeterInterval() {
        return new MeterInterval();
    }

    /**
     * Create an instance of {@link ThermometerChart }
     * 
     */
    public ThermometerChart createThermometerChart() {
        return new ThermometerChart();
    }

    /**
     * Create an instance of {@link ThermometerPlot }
     * 
     */
    public ThermometerPlot createThermometerPlot() {
        return new ThermometerPlot();
    }

    /**
     * Create an instance of {@link LowRange }
     * 
     */
    public LowRange createLowRange() {
        return new LowRange();
    }

    /**
     * Create an instance of {@link MediumRange }
     * 
     */
    public MediumRange createMediumRange() {
        return new MediumRange();
    }

    /**
     * Create an instance of {@link HighRange }
     * 
     */
    public HighRange createHighRange() {
        return new HighRange();
    }

    /**
     * Create an instance of {@link MultiAxisChart }
     * 
     */
    public MultiAxisChart createMultiAxisChart() {
        return new MultiAxisChart();
    }

    /**
     * Create an instance of {@link MultiAxisPlot }
     * 
     */
    public MultiAxisPlot createMultiAxisPlot() {
        return new MultiAxisPlot();
    }

    /**
     * Create an instance of {@link Axis }
     * 
     */
    public Axis createAxis() {
        return new Axis();
    }

    /**
     * Create an instance of {@link StackedAreaChart }
     * 
     */
    public StackedAreaChart createStackedAreaChart() {
        return new StackedAreaChart();
    }

    /**
     * Create an instance of {@link GanttChart }
     * 
     */
    public GanttChart createGanttChart() {
        return new GanttChart();
    }

    /**
     * Create an instance of {@link GanttDataset }
     * 
     */
    public GanttDataset createGanttDataset() {
        return new GanttDataset();
    }

    /**
     * Create an instance of {@link GanttSeries }
     * 
     */
    public GanttSeries createGanttSeries() {
        return new GanttSeries();
    }

    /**
     * Create an instance of {@link TaskExpression }
     * 
     */
    public TaskExpression createTaskExpression() {
        return new TaskExpression();
    }

    /**
     * Create an instance of {@link SubtaskExpression }
     * 
     */
    public SubtaskExpression createSubtaskExpression() {
        return new SubtaskExpression();
    }

    /**
     * Create an instance of {@link PercentExpression }
     * 
     */
    public PercentExpression createPercentExpression() {
        return new PercentExpression();
    }

    /**
     * Create an instance of {@link ElementGroup }
     * 
     */
    public ElementGroup createElementGroup() {
        return new ElementGroup();
    }

    /**
     * Create an instance of {@link Crosstab }
     * 
     */
    public Crosstab createCrosstab() {
        return new Crosstab();
    }

    /**
     * Create an instance of {@link CrosstabParameter }
     * 
     */
    public CrosstabParameter createCrosstabParameter() {
        return new CrosstabParameter();
    }

    /**
     * Create an instance of {@link ParameterValueExpression }
     * 
     */
    public ParameterValueExpression createParameterValueExpression() {
        return new ParameterValueExpression();
    }

    /**
     * Create an instance of {@link CrosstabDataset }
     * 
     */
    public CrosstabDataset createCrosstabDataset() {
        return new CrosstabDataset();
    }

    /**
     * Create an instance of {@link CrosstabColumnCell }
     * 
     */
    public CrosstabColumnCell createCrosstabColumnCell() {
        return new CrosstabColumnCell();
    }

    /**
     * Create an instance of {@link CrosstabHeaderCell }
     * 
     */
    public CrosstabHeaderCell createCrosstabHeaderCell() {
        return new CrosstabHeaderCell();
    }

    /**
     * Create an instance of {@link CellContents }
     * 
     */
    public CellContents createCellContents() {
        return new CellContents();
    }

    /**
     * Create an instance of {@link Frame }
     * 
     */
    public Frame createFrame() {
        return new Frame();
    }

    /**
     * Create an instance of {@link ComponentElement }
     * 
     */
    public ComponentElement createComponentElement() {
        return new ComponentElement();
    }

    /**
     * Create an instance of {@link GenericElement }
     * 
     */
    public GenericElement createGenericElement() {
        return new GenericElement();
    }

    /**
     * Create an instance of {@link GenericElementType }
     * 
     */
    public GenericElementType createGenericElementType() {
        return new GenericElementType();
    }

    /**
     * Create an instance of {@link GenericElementParameter.ValueExpression }
     * 
     */
    public GenericElementParameter.ValueExpression createGenericElementParameterValueExpression() {
        return new GenericElementParameter.ValueExpression();
    }

    /**
     * Create an instance of {@link RowGroup }
     * 
     */
    public RowGroup createRowGroup() {
        return new RowGroup();
    }

    /**
     * Create an instance of {@link Bucket }
     * 
     */
    public Bucket createBucket() {
        return new Bucket();
    }

    /**
     * Create an instance of {@link BucketExpression }
     * 
     */
    public BucketExpression createBucketExpression() {
        return new BucketExpression();
    }

    /**
     * Create an instance of {@link OrderByExpression }
     * 
     */
    public OrderByExpression createOrderByExpression() {
        return new OrderByExpression();
    }

    /**
     * Create an instance of {@link ComparatorExpression }
     * 
     */
    public ComparatorExpression createComparatorExpression() {
        return new ComparatorExpression();
    }

    /**
     * Create an instance of {@link CrosstabRowHeader }
     * 
     */
    public CrosstabRowHeader createCrosstabRowHeader() {
        return new CrosstabRowHeader();
    }

    /**
     * Create an instance of {@link CrosstabTotalRowHeader }
     * 
     */
    public CrosstabTotalRowHeader createCrosstabTotalRowHeader() {
        return new CrosstabTotalRowHeader();
    }

    /**
     * Create an instance of {@link ColumnGroup }
     * 
     */
    public ColumnGroup createColumnGroup() {
        return new ColumnGroup();
    }

    /**
     * Create an instance of {@link CrosstabHeader }
     * 
     */
    public CrosstabHeader createCrosstabHeader() {
        return new CrosstabHeader();
    }

    /**
     * Create an instance of {@link CrosstabColumnHeader }
     * 
     */
    public CrosstabColumnHeader createCrosstabColumnHeader() {
        return new CrosstabColumnHeader();
    }

    /**
     * Create an instance of {@link CrosstabTotalColumnHeader }
     * 
     */
    public CrosstabTotalColumnHeader createCrosstabTotalColumnHeader() {
        return new CrosstabTotalColumnHeader();
    }

    /**
     * Create an instance of {@link Measure }
     * 
     */
    public Measure createMeasure() {
        return new Measure();
    }

    /**
     * Create an instance of {@link MeasureExpression }
     * 
     */
    public MeasureExpression createMeasureExpression() {
        return new MeasureExpression();
    }

    /**
     * Create an instance of {@link CrosstabCell }
     * 
     */
    public CrosstabCell createCrosstabCell() {
        return new CrosstabCell();
    }

    /**
     * Create an instance of {@link WhenNoDataCell }
     * 
     */
    public WhenNoDataCell createWhenNoDataCell() {
        return new WhenNoDataCell();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link PartNameExpression }
     * 
     */
    public PartNameExpression createPartNameExpression() {
        return new PartNameExpression();
    }

    /**
     * Create an instance of {@link GroupFooter }
     * 
     */
    public GroupFooter createGroupFooter() {
        return new GroupFooter();
    }

    /**
     * Create an instance of {@link Background }
     * 
     */
    public Background createBackground() {
        return new Background();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link PageHeader }
     * 
     */
    public PageHeader createPageHeader() {
        return new PageHeader();
    }

    /**
     * Create an instance of {@link ColumnHeader }
     * 
     */
    public ColumnHeader createColumnHeader() {
        return new ColumnHeader();
    }

    /**
     * Create an instance of {@link Detail }
     * 
     */
    public Detail createDetail() {
        return new Detail();
    }

    /**
     * Create an instance of {@link ColumnFooter }
     * 
     */
    public ColumnFooter createColumnFooter() {
        return new ColumnFooter();
    }

    /**
     * Create an instance of {@link PageFooter }
     * 
     */
    public PageFooter createPageFooter() {
        return new PageFooter();
    }

    /**
     * Create an instance of {@link LastPageFooter }
     * 
     */
    public LastPageFooter createLastPageFooter() {
        return new LastPageFooter();
    }

    /**
     * Create an instance of {@link Summary }
     * 
     */
    public Summary createSummary() {
        return new Summary();
    }

    /**
     * Create an instance of {@link NoData }
     * 
     */
    public NoData createNoData() {
        return new NoData();
    }

    /**
     * Create an instance of {@link MultiAxisData }
     * 
     */
    public MultiAxisData createMultiAxisData() {
        return new MultiAxisData();
    }

    /**
     * Create an instance of {@link MultiAxisDataset }
     * 
     */
    public MultiAxisDataset createMultiAxisDataset() {
        return new MultiAxisDataset();
    }

    /**
     * Create an instance of {@link DataAxis }
     * 
     */
    public DataAxis createDataAxis() {
        return new DataAxis();
    }

    /**
     * Create an instance of {@link AxisLevel.LabelExpression }
     * 
     */
    public AxisLevel.LabelExpression createAxisLevelLabelExpression() {
        return new AxisLevel.LabelExpression();
    }

    /**
     * Create an instance of {@link AxisLevelBucket.LabelExpression }
     * 
     */
    public AxisLevelBucket.LabelExpression createAxisLevelBucketLabelExpression() {
        return new AxisLevelBucket.LabelExpression();
    }

    /**
     * Create an instance of {@link BucketProperty }
     * 
     */
    public BucketProperty createBucketProperty() {
        return new BucketProperty();
    }

    /**
     * Create an instance of {@link MultiAxisMeasure.LabelExpression }
     * 
     */
    public MultiAxisMeasure.LabelExpression createMultiAxisMeasureLabelExpression() {
        return new MultiAxisMeasure.LabelExpression();
    }

    /**
     * Create an instance of {@link MultiAxisMeasure.ValueExpression }
     * 
     */
    public MultiAxisMeasure.ValueExpression createMultiAxisMeasureValueExpression() {
        return new MultiAxisMeasure.ValueExpression();
    }

    /**
     * Create an instance of {@link ExpressionReturnValue.Expression }
     * 
     */
    public ExpressionReturnValue.Expression createExpressionReturnValueExpression() {
        return new ExpressionReturnValue.Expression();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyExpressionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PropertyExpressionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://jasperreports.sourceforge.net/jasperreports", name = "propertyExpression")
    public JAXBElement<PropertyExpressionType> createPropertyExpression(PropertyExpressionType value) {
        return new JAXBElement<PropertyExpressionType>(_PropertyExpression_QNAME, PropertyExpressionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://jasperreports.sourceforge.net/jasperreports", name = "patternExpression")
    public JAXBElement<Object> createPatternExpression(Object value) {
        return new JAXBElement<Object>(_PatternExpression_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ComponentType }{@code >}
     */
    @XmlElementDecl(namespace = "http://jasperreports.sourceforge.net/jasperreports", name = "component")
    public JAXBElement<ComponentType> createComponent(ComponentType value) {
        return new JAXBElement<ComponentType>(_Component_QNAME, ComponentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartComponentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PartComponentType }{@code >}
     */
    @XmlElementDecl(namespace = "http://jasperreports.sourceforge.net/jasperreports", name = "partComponent")
    public JAXBElement<PartComponentType> createPartComponent(PartComponentType value) {
        return new JAXBElement<PartComponentType>(_PartComponent_QNAME, PartComponentType.class, null, value);
    }

}
